### ISSUE TITLE
Is the word “pregenitor” correct, or a typo?

### ISSUE THREAD

**Issue by AlbertoGP** [pyjarrett/programming-with-ada#1]
Hi, in the “Terminology” section (https://github.com/pyjarrett/programming-with-ada/blob/main/source/900-comparison.rst), is “pregenitor” a concept in Ada, or a typo for “progenitor”?
Neither word appears anywhere else in the document.

**Comment by pyjarrett** [comment]
It's a typo.  Thanks for the catch!

Fixed: 8550d7f18f6075704a3f4fb0e2967b13a02d02f9
